CREATE TABLE IF NOT EXISTS league_player_stats(
        ign varchar(70) not null,
        division_name varchar(70) NOT NULL,
        team_name varchar(70),
        discord_id bigint default NULL,
        damage_taken int NOT NULL default 0,
        damage_mitigated int NOT NULL default 0,
        player_damage int NOT NULL default 0,
        loser boolean NOT NULL ,
        winner boolean NOT NULL,
        kills int NOT NULL default 0,
        deaths int NOT NULL default 0,
        assists int NOT NULL default 0,
        gold_earned int NOT NULL default 0,
        wards_placed int NOT NULL default 0,
        total_match_duration int NOT NULL default 0,
        first_blood_kills int NOT NULL default 0,
        self_heal int NOT NULL default 0,
        damage_physical_dealt int NOT NULL default 0,
        damage_magical_dealt int NOT NULL default 0,
        item1 varchar(70),
        item2 varchar(70),
        item3 varchar(70),
        item4 varchar(70),
        item5 varchar(70),
        item6 varchar(70),
        active1 varchar(70),
        active2 varchar(70),
        match_id bigint not null,

        PRIMARY KEY (ign,division_name,match_id),
        FOREIGN KEY (division_Name) references division(division_name)
);